EmployeesDemoMVC/Controllers/ArtistController.cs
using Chinook.BusinessLogic;
using Chinook.BusinessLogic.Interface;
using Chinook.BusinessModel.Models;
using ChinookDemoMVC.Controllers.FoxyPos.Api.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace ChinookDemoMVC.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ArtistController : BaseController<Artist>
    {
        public ArtistController(IObjectFactory factory) : base()
        {
            _manager = factory.Resolve<IArtistManager>();
        }
         
        [HttpGet]
         public IActionResult Index()
        {
            var artist = new Artist();
            artist.Name = "Mika";
            _manager.Add(artist);
            return View("~/Views/Crud/Artist.cshtml");
        }

    }
}

EmployeesDemoMVC/Controllers/ClientController.cs
using Chinook.BusinessLogic;
using Chinook.BusinessLogic.Interface;
using Chinook.BusinessModel.Models;
using ChinookDemoMVC.Controllers.FoxyPos.Api.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ChinookDemoMVC.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ClientController : BaseController<Client>
    {
        private readonly IEmployeeManager _employeeManager;

        public ClientController(IObjectFactory factory) : base()
        {
            _manager = factory.Resolve<IClientManager>();
            _employeeManager = factory.Resolve<IEmployeeManager>();
            _mainCrudView = "~/Views/Client/Index.cshtml";
        }

      
        [HttpGet]
        [Route("[action]")]
        public IActionResult Create()
        {
            var employees = _employeeManager.List().ToList();
            ViewData["Employees"] = employees;

            return View("~/Views/Client/Create.cshtml");
        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Store(IFormCollection form)
        {
            var client = new Client();
            client.Name = form["Name"].ToString();
            client.LastName = form["LastName"].ToString();
            client.Email = form["Email"].ToString();
            client.Phone = form["Phone"].ToString();

            Console.WriteLine("Support: " + form["Support"].ToString());

            if (form["Support"].ToString() != "")
            {
                client.SupportEmployeeId = long.Parse(form["Support"].ToString());
            }

            await _manager.Add(client);

            return Redirect("/Client");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public IActionResult Edit(long id)
        {
            var client = _manager.Get(id).Result;
            var clientItems = _employeeManager.List().ToList();

            if (client == null)
            {
                return Redirect("/Client");
            }

            ViewData["Current"] = client;
            ViewData["Employees"] = clientItems;

            return View("~/Views/Client/Edit.cshtml");

        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Change(IFormCollection form)
        {
            var client = new Client();
            client.ClientId = long.Parse(form["Id"].ToString());
            client.Name = form["Name"].ToString();
            client.LastName = form["LastName"].ToString();
            client.Email = form["Email"].ToString();
            client.Phone = form["Phone"].ToString();

            Console.WriteLine("Support: " + form["Support"].ToString());

            if (form["Support"].ToString() != "")
            {
                client.SupportEmployeeId = long.Parse(form["Support"].ToString());
            }

            await _manager.Modify(client.ClientId, client);

            return Redirect("/Client");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public virtual async Task<IActionResult> Remove(long id)
        {
            await _manager.Delete(id);
            return Redirect("/Client");
        }
    }
}

EmployeesDemoMVC/Controllers/EmployeeController.cs
using Chinook.BusinessLogic;
using Chinook.BusinessLogic.Interface;
using Chinook.BusinessModel.Models;
using ChinookDemoMVC.Controllers.FoxyPos.Api.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ChinookDemoMVC.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class EmployeeController : BaseController<Employee>
    {
        private readonly IEmployeeManager _employeeManager;

        public EmployeeController(IObjectFactory factory) : base()
        {
            _employeeManager = factory.Resolve<IEmployeeManager>();
            _manager = factory.Resolve<IEmployeeManager>();
            _mainCrudView = "~/Views/Employee/Index.cshtml";
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult Create()
        {
            var employees = _employeeManager.List().ToList();
            ViewData["Employees"] = employees;

            return View("~/Views/Employee/Create.cshtml");
        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Store(IFormCollection form)
        {
            var employee = new Employee();
            employee.Name = form["Name"].ToString();
            employee.LastName = form["LastName"].ToString();
            employee.Email = form["Email"].ToString();
            employee.Phone = form["Phone"].ToString();
            employee.JobPosition = form["JobPosition"].ToString();

            Console.WriteLine("DirectBoss: " + form["DirectBoss"].ToString());

            if (form["DirectBoss"].ToString() != "")
            {
                employee.DirectBossEmployeeId = long.Parse(form["DirectBoss"].ToString());
            }
            
            await _employeeManager.Add(employee);

            return Redirect("/Employee");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public IActionResult Edit(long id)
        {
            var employee = _employeeManager.Get(id).Result;
            var employeeItems = _employeeManager.List().ToList();

            if (employee == null)
            {
                return Redirect("/Employee");
            }

            ViewData["Current"] = employee;
            ViewData["Employees"] = employeeItems;

            return View("~/Views/Employee/Edit.cshtml");

        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Change(IFormCollection form)
        {
            var employee = new Employee();
            employee.EmployeeId = long.Parse(form["Id"].ToString());
            employee.Name = form["Name"].ToString();
            employee.LastName = form["LastName"].ToString();
            employee.Email = form["Email"].ToString();
            employee.Phone = form["Phone"].ToString();
            employee.JobPosition = form["JobPosition"].ToString();

            Console.WriteLine("DirectBoss: " + form["DirectBoss"].ToString());

            if(form["DirectBoss"].ToString() != "")
            {
                employee.DirectBossEmployeeId = long.Parse(form["DirectBoss"].ToString());
            }

            await _employeeManager.Modify(employee.EmployeeId, employee);

            return Redirect("/Employee");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public virtual async Task<IActionResult> Remove(long id)
        {
            await _employeeManager.Delete(id);
            return Redirect("/Employee");
        }
    }
}

EmployeesDemoMVC/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Chinook.BusinessLogic;
using Chinook.BusinessLogic.Interface;
using Chinook.BusinessModel.Models;
using ChinookDemoMVC.Controllers.FoxyPos.Api.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ChinookDemoMVC.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class SongController : BaseController<Song>
    {
        private readonly IBaseManager<Album> _albumManager;
        private readonly IBaseManager<Genre> _genreManager;
        private readonly ISongManager _songManager;
        private readonly ILogger<SongController> _logger;
        public SongController(IObjectFactory factory, ILogger<SongController> logger) : base()
        {
            //_manager = factory.Resolve<ISongManager>();
            _albumManager = factory.Resolve<IAlbumManager>();
            _genreManager = factory.Resolve<IGenreManager>();
            _songManager = factory.Resolve<ISongManager>();
            _logger = logger;
            _manager = factory.Resolve<ISongManager>();
            _mainCrudView = "~/Views/Song/Index.cshtml";
        }


        [HttpGet]
        override
        public IActionResult Index(int page = 1, int pageSize = _defaultPageSize)
        {
            var query = _songManager.GetIncluded();
            var itemCount = query.Count();
            int? pages = GetPages(itemCount, page, pageSize);

            query = Paginate(query, page);
            var items = query.ToList();

            ViewData["ListItems"] = items;
            ViewData["Pages"] = pages;
            ViewData["CurrentPage"] = page;
            return View("~/Views/Song/Index.cshtml");
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult Create()
        {
           
            var query = _genreManager.List();
            var queryAlbum = _albumManager.List();
            var genres =      query.ToList();
            var albumItems =   queryAlbum.ToList();
            ViewData["GenreItems"] = genres;
            ViewData["AlbumItems"] = albumItems;
            return View("~/Views/Song/Create.cshtml");
        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Store(IFormCollection collection)
        {
            var song = new Song();
            song.Name = collection["Name"].ToString();
            long albumId = long.Parse(collection["Album"].ToString());
            long genreId = long.Parse(collection["Genre"].ToString());

            //song.Album = _albumManager.Get(albumId).Result;
            //song.Genre = _genreManager.Get(genreId).Result;
            song.AlbumId = albumId;
            song.GenreId = genreId;

            /*song.AlbumId = albumId;
            song.GenreId = genreId;*/

            Console.WriteLine("AlbumId: " + song.AlbumId);
            Console.WriteLine("GenreId: " + song.GenreId);

            

            await _songManager.Add(song);


            return Redirect("/Song");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public IActionResult Edit(long id)
        {
            var query = _genreManager.List();
            var queryAlbum = _albumManager.List();
            var genres = query.ToList();
            var albumItems = queryAlbum.ToList();

            var song = _songManager.Get(id).Result;

            ViewData["GenreItems"] = genres;
            ViewData["AlbumItems"] = albumItems;
            ViewData["CurrentSong"] = song;
            return View("~/Views/Song/Edit.cshtml");
        }

        [HttpPost]
        [Route("[action]")]
        public virtual async Task<IActionResult> Change(IFormCollection form)
        {
            long id = long.Parse(form["Id"].ToString());
            var song = new Song();

            song.Name = form["Name"].ToString();
            song.AlbumId = long.Parse(form["Album"].ToString());
            song.GenreId = long.Parse(form["Genre"].ToString());
            song.SongId = id;

            await _songManager.Modify(id, song);

            return Redirect("/Song");
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public virtual async Task<IActionResult> Remove(long id)
        {

            await _songManager.Delete(id);
            return Redirect("/Song");
        }

        [HttpGet("search-all/")]
        override
        public async Task<ActionResult<Song>> SearchAllFields(string filterValue = null, string sortProperty = null, int? pageNumber = 1, int pageSize = _defaultPageSize)
        {
            try
            {
                var query = _songManager.SearchAllIncluded(filterValue, sortProperty);
                var itemCount = query.Count();
                int? pages = GetPages(itemCount, pageNumber, pageSize);

                if (pageNumber.HasValue)
                    query = Paginate(query, pageNumber.Value);

                var items = query.ToList();

                ViewData["ListItems"] = items;
                ViewData["Pages"] = pages;
                ViewData["CurrentPage"] = pageNumber;


                return View("~/Views/Song/Index.cshtml");
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
                LogManager.Current.Log.Error(e);
                return StatusCode(500, "Internal Server Error " + e.Message);
            }
        }
    }
}

EmployeesDemoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeesDemoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/select2.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeesDemoMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Canciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Género</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Empleados</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeesDemoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/alpine.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EmployeesDemoMVC/Views/Shared/_PaginationBar.cshtml
@using Microsoft.AspNetCore.Http.Extensions;
@using System.Text.RegularExpressions

<style>
    .center {
        text-align: center;
    }

    .pagination {
        display: inline-block;
    }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
            border: 1px solid #ddd;
            margin: 0 4px;
        }

            .pagination a.active {
                background-color: #4CAF50;
                color: white;
                border: 1px solid #4CAF50;
            }

            .pagination a:hover:not(.active) {
                background-color: #ddd;
            }
</style>


<div class="center my-5">
    <div class="pagination">
        <a href="#">&laquo;</a>
        @for (int i = 1; i <= Int32.Parse(ViewBag.Pages.ToString()); i++)
        {
            <!--im aware of the performance cost of using a regex-->
            String nextPage;

            string queryString = Url.ActionContext.HttpContext.Request.QueryString.ToString();
            string parameterToRemove = "PageNumber";   //parameter which we want to remove
            string regex = string.Format("(&{0}=[^&\\s]+|{0}=[^&\\s]+&?)", parameterToRemove);

            string finalQS = Regex.Replace(queryString, regex, "");

            if (Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("?") != -1)
            {
                nextPage = Url.ActionContext.HttpContext.Request.GetDisplayUrl().Substring(0, Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("?"));
                nextPage = nextPage.Replace("?", "");
                if (finalQS != "?")
                {
                    nextPage += finalQS + "&PageNumber=" + i;
                }
                else
                {
                    nextPage += finalQS + "PageNumber=" + i;
                }
            }
            else
                nextPage = Url.ActionContext.HttpContext.Request.GetDisplayUrl() + "?PageNumber=" + i + finalQS;

            if (i == Int32.Parse(ViewBag.CurrentPage.ToString()))
            {
                <a class="nav-link text-dark active" href="@nextPage" asp-pageNumber="@i">@i</a>
            }
            else
            {
                <a class="nav-link text-dark" href="@nextPage">@i</a>
            }
        }
        <a href="#">&raquo;</a>
    </div>
</div>

EmployeesDemoMVC/Views/Shared/_SearchBar.cshtml
@using Microsoft.AspNetCore.Http.Extensions;
@using System.Text.RegularExpressions

<style>
    #search {
        display: flex;
        align-items: center;
    }

    #search-p {
        margin-bottom: 0;
        margin-top: 0;
    }
</style>

<div class="input-group md-form form-sm form-2 pl-0 my-4">
    <input id="searchBar" class="form-control my-0 py-1 red-border" type="text" placeholder="Type and press Buscar" aria-label="Search" style="height:50px;">
    <div class="input-group-append">
        <button class="input-group-text btn btn-success" id="search" style="height:50px;" onclick="search()">
            <p>Buscar</p>
        </button>
    </div>
</div>


<script>
    var url = "@Url.ActionContext.HttpContext.Request.GetEncodedUrl()";

     @{
         string queryString = Url.ActionContext.HttpContext.Request.QueryString.ToString();
         string parameterToRemove = "FilterValue";   //parameter which we want to remove
         string regex = string.Format("(&{0}=[^&\\s]+|{0}=[^&\\s]+&?)", parameterToRemove);
         string nextPage;

         string finalQS = Regex.Replace(queryString, regex, "");


         if (Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("?") != -1)
         {
             nextPage = Url.ActionContext.HttpContext.Request.GetEncodedUrl().Substring(0, Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("?"));
             nextPage = nextPage.Replace("?", "");

             if (Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("search-all/") == -1)
             {
                 nextPage += "/search-all/";
             }
    
             if (finalQS != "?")
             {
                 nextPage += finalQS + "&FilterValue=";
             }
             else
             {
                 nextPage += finalQS + "FilterValue=";
             }
         }
         else
         {
             nextPage = Url.ActionContext.HttpContext.Request.GetEncodedUrl();

             if (Url.ActionContext.HttpContext.Request.GetDisplayUrl().IndexOf("search-all/") == -1)
             {
                 nextPage += "/search-all/";
             }

            nextPage += "?" + finalQS + "FilterValue=";
         }


         <text>
        var searchString = decodeURIComponent("@Html.Raw(nextPage)");
        function search() {;
            var filterValue = document.getElementById("searchBar").value;
            window.location.href = decodeURIComponent(searchString + filterValue);
        }
         </text>
     }
</script>