EmployeesDemoMVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Chinook.BusinessModel.Models;
using ChinookDemoMVC.Controllers.FoxyPos.Api.Controllers;
using Chinook.BusinessLogic;
using Chinook.BusinessLogic.Interface;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Diagnostics;

namespace ChinookDemoMVC.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class GenreController : BaseController<Genre>
    {

        public GenreController(IObjectFactory factory) : base()
        {
            _manager = factory.Resolve<IGenreManager>();
        }


        [HttpGet]
        public override IActionResult Index(int page = 1, int pageSize = _defaultPageSize)
        {
            var query = _manager.List();
            var itemCount = query.Count();
            int? pages = GetPages(itemCount, page, pageSize);

            query = Paginate(query, page);
            var items = query.ToList();

            ViewData["ListItems"] = items;
            ViewData["Pages"] = pages;
            ViewData["CurrentPage"] = page;
            return View("~/Views/Genre/Index.cshtml");
        }

        [HttpDelete]
        public async Task<ActionResult<Genre>> Delete(int id)
        {
            try
            {
                var item = await _manager.Delete(id);
                if (item == null)
                {
                    return NotFound();
                }

                ViewData["DeletedItem"] = item;
                ViewData["Deleted"] = true;
                return View("~/Views/Genre/Index.cshtml");
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
                LogManager.Current.Log.Error(e);
                return StatusCode(500, "Internal Server Error " + e.Message);
            }
        }

        [HttpPut]
        public virtual async Task<IActionResult> Put(long id, [FromForm]Genre item)
        {
            try
            {
                if (id != item.Key)
                {
                    return BadRequest();
                }

                bool result = await _manager.Modify(id, item);

                if (result == false)
                {
                    return NotFound();
                }

                ViewData["Modified"] = true;
                return View("~/Views/Genre/Index.cshtml");
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
                LogManager.Current.Log.Error(e);
                return StatusCode(500, "Internal Server Error " + e.Message);
            }

        }

    }
}

EmployeesDemoMVC/Views/Genre/Create.cshtml
@{
    ViewData["Title"] = "Crear Género";
}


<div class="d-flex justify-content-center">
    
    <form method="post" class="w-75" asp-controller="Genre" asp-action="Store" enctype="multipart/form-data">
        <h4>Crear género</h4>
        <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text" class="form-control" id="name" name="Name" required aria-describedby="name">
        </div>
        
        
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>

EmployeesDemoMVC/Views/Genre/Index.cshtml
@using Chinook.BusinessModel.Models
@using Microsoft.AspNetCore.Http.Extensions;
@model Genre
@{
    ViewData["Title"] = "Géneros musicales";
    var genres = (List<Genre>)ViewBag.ListItems;

}
<h1>Géneros</h1>

<div class="my-5">
    @using (Html.BeginForm("Post", "Genre", FormMethod.Post))
    {
        <strong class="pr-2">Nombre </strong> @Html.EditorFor(m => m.Name)
        <br />
        <input class="btn btn-success btn-sm my-3" id="Submit" type="submit" value="Crear Género">
    }
</div>


<table id="table" class="display" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var genre in genres)
        {
            <tr>
                <td>@genre.GenreId</td>
                <td>@genre.Name</td>
                <td><input class="btn btn-danger btn-sm my-3" id="Submit" type="submit" value="Borrar Género" onclick="deleteItem(@genre.GenreId)"></td>
            </tr>
        }
    </tbody>
</table>

<script>
@if(ViewData["Deleted"] != null)
{
    if ((bool)ViewData["Deleted"])
    {
    <text>
    alert('Eliminado');
    </text>
    }
}



@if(ViewData["Modified"] != null)
{
    if ((bool)ViewData["Modified"])
    {
    <text>
    alert('Modificado');
    </text>
    }
}

    $(document).ready(function () {
        $('#table').DataTable({
            buttons: [
                {
                    extend: 'remove',
                    editor: myEditor
                }
            ]
        });
    });

    function deleteItem(itemId){
        return fetch('@Url.ActionContext.HttpContext.Request.GetEncodedUrl()/json/' + itemId, {
            method: 'Delete'
        }).then(response => {
            if (response.status == 200) {
                alert('Eliminado');
                window.location.replace('@Url.ActionContext.HttpContext.Request.GetEncodedUrl()');
                return;
            } });
    }
</script>